spring.application.name: stock-service

spring.kafka.bootstrap-servers: ${KAFKA_URL}
spring.cloud.stream.kafka.streams.binder.configuration:
  security.protocol: SASL_SSL
  sasl:
    mechanism: PLAIN
    jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="${KAFKA_USER}" password="${KAFKA_PASSWORD}";

# example template to copy
spring.cloud.stream.bindings.<name>-in-0.destination: <in-0-stream>
spring.cloud.stream.bindings.<name>-in-1.destination: <in-1-stream>
spring.cloud.stream.kafka.streams.binder.functions.<name>.applicationId: <unique_name>

spring.output.ansi.enabled: ALWAYS

logging.pattern.console: "%clr(%d{HH:mm:ss.SSS}){blue} %clr(---){faint} %clr([%15.15t]){yellow} %clr(:){red} %clr(%m){faint}%n"

management.endpoints.web.exposure.include: "*"