spring.application.name: order-service

spring.kafka.bootstrap-servers: ${KAFKA_URL}

spring.cloud.stream.function.definition: orderBuySupplier;orderSellSupplier

spring.cloud.stream.bindings.orderBuySupplier-out-0.destination: streams.pminkows.orders.buy
#spring.cloud.stream.bindings.orderBuySupplier-out-0.producer.partitionKeyExpression: payload.type
#spring.cloud.stream.bindings.orderBuySupplier-out-0.producer.partitionCount: 2
spring.cloud.stream.kafka.bindings.orderBuySupplier-out-0.producer.configuration.key.serializer: org.apache.kafka.common.serialization.LongSerializer

spring.cloud.stream.bindings.orderSellSupplier-out-0.destination: streams.pminkows.orders.sell
#spring.cloud.stream.bindings.orderSellSupplier-out-0.producer.partitionKeyExpression: payload.type
#spring.cloud.stream.bindings.orderSellSupplier-out-0.producer.partitionCount: 3
spring.cloud.stream.kafka.bindings.orderSellSupplier-out-0.producer.configuration.key.serializer: org.apache.kafka.common.serialization.LongSerializer


spring.output.ansi.enabled: ALWAYS

logging.pattern.console: "%clr(%d{HH:mm:ss.SSS}){blue} %clr(---){faint} %clr([%15.15t]){yellow} %clr(:){red} %clr(%m){faint}%n"